version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

commands:
  bootsnap_cache:
    steps:
      - restore_cache:
          keys:
            - bootsnap-cache-{{ .Branch }}-{{ .Revision }}
            - bootsnap-cache-{{ .Branch }}
            - bootsnap-cache
      - save_cache:
          key: bootsnap-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - tmp/cache/bootsnap-load-path-cache
            - tmp/cache/bootsnap-compile-cache
      - save_cache:
          key: bootsnap-cache-{{ .Branch }}
          paths:
            - tmp/cache/bootsnap-load-path-cache
            - tmp/cache/bootsnap-compile-cache
      - save_cache:
          key: bootsnap-cache
          paths:
            - tmp/cache/bootsnap-load-path-cache
            - tmp/cache/bootsnap-compile-cache

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
    executor: ruby/default
    steps:
      - checkout
      - bootsnap_cache
      - run: yarn install
      - run: bundle update --bundler
      - run: bundle install
      - restore_cache:
          keys:
            - v1-bootsnap-cache-{{ checksum "Gemfile.lock" }}-{{ .Branch }}
            - v1-bootsnap-cache-{{ checksum "Gemfile.lock" }}-master
      - run: bundle exec bin/webpack
      - run: bundle exec rails db:create db:migrate RAILS_ENV=test
      - run: bundle exec rspec
      - save_cache:
          key: v1-bootsnap-cache-{{ checksum "Gemfile.lock" }}-{{ .Branch }}-{{ epoch }}
          paths:
            - tmp/bootsnap_cache
